#!/usr/bin/env python3
"""Generate Asterisk pjsip trunk config from the dashboard database.

Reads SIP providers you added in the dashboard and writes
asterisk/pjsip_trunks.conf. Run via scripts/apply-trunks.sh (which then
reloads Asterisk). No manual pjsip editing needed.

Auth mode is inferred:
  * username + password present -> registration trunk
  * host only (no credentials)  -> IP-based trunk (give the provider your IP)
"""
import os
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)  # selfhosted/
DB = os.environ.get("DASHBOARD_DB", os.path.join(ROOT, "dashboard-data", "dashboard.db"))
OUT = os.environ.get("TRUNKS_OUT", os.path.join(ROOT, "asterisk-generated", "pjsip_trunks.conf"))

HEADER = (
    "; AUTO-GENERATED by scripts/gen_trunks.py - do not edit by hand.\n"
    "; Manage SIP Providers in the dashboard, then run scripts/apply-trunks.sh\n\n"
)


def s(v):
    return (v or "").strip()


def trunk_block(i, p):
    host = s(p["host"])
    if not host:
        return ""  # a trunk needs at least a host
    name = f"trunk{i}"
    user, pw = s(p["username"]), s(p["password"])
    register = bool(user and pw)
    out = [f"; --- {s(p['name'])} ---"]
    if register:
        out += [
            f"[{name}-reg]", "type=registration", "transport=transport-udp",
            f"outbound_auth={name}-auth", f"server_uri=sip:{host}",
            f"client_uri=sip:{user}@{host}", "retry_interval=60", "",
            f"[{name}-auth]", "type=auth", "auth_type=userpass",
            f"username={user}", f"password={pw}", "",
        ]
    out += [
        f"[{name}-aor]", "type=aor", f"contact=sip:{host}", "",
        f"[{name}]", "type=endpoint", "transport=transport-udp", "context=ai",
        "disallow=all", "allow=ulaw", "allow=alaw", f"aors={name}-aor",
    ]
    if register:
        out += [f"outbound_auth={name}-auth", f"from_user={user}"]
    out += ["", f"[{name}-identify]", "type=identify", f"endpoint={name}", f"match={host}", ""]
    return "\n".join(out) + "\n"


def main():
    text = HEADER
    rows = []
    if os.path.exists(DB):
        con = sqlite3.connect(DB)
        con.row_factory = sqlite3.Row
        try:
            rows = con.execute("SELECT * FROM providers WHERE active=1 ORDER BY id").fetchall()
        except sqlite3.OperationalError:
            rows = []
        con.close()
    else:
        sys.stderr.write(f"(dashboard DB not found at {DB}; writing empty trunks)\n")

    count = 0
    for p in rows:
        block = trunk_block(p["id"], p)
        if block:
            text += block + "\n"
            count += 1
    if count == 0:
        text += "; (no active SIP providers configured yet)\n"

    with open(OUT, "w") as f:
        f.write(text)
    print(f"Wrote {OUT} ({count} trunk(s)).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
